// #8 lift: byte-index into an element of a `bytes[]` field of a CALLDATA dynamic-struct-array element
// (xs[i].tags[j][k], xs: P[] calldata, P { tags: bytes[] }). solc reads the byte directly from calldata;
// JETH previously rejected it (JETH151, a mapping-resolver misfire on the deep element-access base). It is
// now byte-identical: it resolves xs[i].tags[j] to the same calldata bytes value the accepted whole-element
// read / bind-a-local workaround produces, then byte-indexes it. The MEMORY twin was already lifted; a
// `string[]` element stays a clean reject (JETH205, not indexable), matching solc. Calldata is generated by
// a solc helper returning abi.encode(xs), so the ABI encoding is exact.
import { describe, it, expect } from 'vitest';
import { compile } from '../src/compile.js';
import { Harness } from '../src/evm.js';
import { compileSolidity } from './_solidity.js';
import { functionSelector } from '../src/selectors.js';

const SPDX = '// SPDX-License-Identifier: MIT\npragma solidity 0.8.35;\n';
const sel = (s: string) => '0x' + functionSelector(s);
const strip = (h: string) => (h.startsWith('0x') ? h.slice(2) : h);
const rejects = (src: string): boolean => {
  try { compile(src, { fileName: 'C.jeth' }); return false; } catch { return true; }
};

describe('#8 lift: calldata bytes[]-field element byte-index xs[i].tags[j][k] - byte-identical to solc 0.8.35', () => {
  it('byte reads / length / whole element / OOB Panic all byte-identical', async () => {
    const h = await Harness.create();
    // exact ABI args for r((bytes[])[]) with xs = [P{tags:["ab","cd","ef"]}]
    const HELP = `struct P { bytes[] tags; }
      contract H { function mk() external pure returns(bytes memory){
        bytes[] memory t=new bytes[](3); t[0]=bytes("ab"); t[1]=bytes("cd"); t[2]=bytes("ef");
        P[] memory xs=new P[](1); xs[0]=P(t); return abi.encode(xs); } }`;
    const ah = await h.deploy(compileSolidity(SPDX + HELP, 'H').creation);
    const raw = strip((await h.call(ah, sel('mk()'))).returnHex);
    const L = parseInt(raw.slice(64, 128), 16);
    const args = raw.slice(128, 128 + L * 2);

    const J = `@struct class P { tags: bytes[]; }
      @contract class C {
        @external @view b00(xs: P[]): bytes1 { return xs[0n].tags[0n][0n]; }
        @external @view b10(xs: P[]): bytes1 { return xs[0n].tags[1n][0n]; }
        @external @view b21(xs: P[]): bytes1 { return xs[0n].tags[2n][1n]; }
        @external @view len(xs: P[]): u256 { return xs[0n].tags.length; }
        @external @view whole(xs: P[]): bytes { return xs[0n].tags[1n]; }
        @external @view oob(xs: P[]): bytes1 { return xs[0n].tags[0n][5n]; } }`;
    const S = `struct P { bytes[] tags; }
      contract C {
        function b00(P[] calldata xs) external pure returns(bytes1){ return xs[0].tags[0][0]; }
        function b10(P[] calldata xs) external pure returns(bytes1){ return xs[0].tags[1][0]; }
        function b21(P[] calldata xs) external pure returns(bytes1){ return xs[0].tags[2][1]; }
        function len(P[] calldata xs) external pure returns(uint256){ return xs[0].tags.length; }
        function whole(P[] calldata xs) external pure returns(bytes memory){ return xs[0].tags[1]; }
        function oob(P[] calldata xs) external pure returns(bytes1){ return xs[0].tags[0][5]; } }`;
    const aj = await h.deploy(compile(J, { fileName: 'C.jeth' }).creationBytecode);
    const as = await h.deploy(compileSolidity(SPDX + S, 'C').creation);
    for (const fn of ['b00', 'b10', 'b21', 'len', 'whole', 'oob']) {
      const data = sel(fn + '((bytes[])[])') + args;
      const rj = await h.call(aj, data);
      const rs = await h.call(as, data);
      expect(rj.success, fn).toBe(rs.success);
      expect(rj.returnHex, fn).toBe(rs.returnHex);
    }
  });

  it('boundaries: memory twin accepts, string[] element rejects (JETH205), value-array element unaffected', () => {
    // memory twin already lifted (byte-identical) - stays accepted
    expect(rejects(`@struct class P { tags: bytes[]; } @contract class C { @external @pure r(): bytes1 { let t: bytes[] = ["ab","cd"]; let xs: P[] = [P(t)]; return xs[0n].tags[0n][0n]; } }`)).toBe(false);
    // string[] element is not byte-indexable in solc either
    expect(rejects(`@struct class PS { tags: string[]; } @contract class C { @external @view r(xs: PS[]): bytes1 { return xs[0n].tags[0n][0n]; } }`)).toBe(true);
    // the accepted whole-element read is unchanged
    expect(rejects(`@struct class P { tags: bytes[]; } @contract class C { @external @view r(xs: P[]): bytes { return xs[0n].tags[0n]; } }`)).toBe(false);
  });
});
